#this is the main UI layout in Python (converted from .ui)
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FastasyCricketGame(object):
    def setupUi(self, FastasyCricketGame):
        FastasyCricketGame.setObjectName("FastasyCricketGame")
        FastasyCricketGame.resize(614, 563)
        self.centralwidget = QtWidgets.QWidget(FastasyCricketGame)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 20, 521, 81))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 60, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 60, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 130, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 130, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 170, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.radioBat = QtWidgets.QRadioButton(self.groupBox)
        self.radioBat.setGeometry(QtCore.QRect(10, 20, 51, 17))
        self.radioBat.setObjectName("radioBat")
        self.radiobow = QtWidgets.QRadioButton(self.groupBox)
        self.radiobow.setGeometry(QtCore.QRect(60, 20, 51, 17))
        self.radiobow.setObjectName("radiobow")
        self.radioar = QtWidgets.QRadioButton(self.groupBox)
        self.radioar.setGeometry(QtCore.QRect(120, 20, 41, 17))
        self.radioar.setObjectName("radioar")
        self.radiowk = QtWidgets.QRadioButton(self.groupBox)
        self.radiowk.setGeometry(QtCore.QRect(170, 20, 41, 17))
        self.radiowk.setObjectName("radiowk")
        self.availablePlayersList = QtWidgets.QListWidget(self.centralwidget)
        self.availablePlayersList.setGeometry(QtCore.QRect(50, 240, 221, 251))
        self.availablePlayersList.setObjectName("availablePlayersList")
        self.selectedPlayersList = QtWidgets.QListWidget(self.centralwidget)
        self.selectedPlayersList.setGeometry(QtCore.QRect(330, 240, 221, 251))
        self.selectedPlayersList.setObjectName("selectedPlayersList")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(50, 220, 81, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(340, 220, 81, 20))
        self.label_11.setObjectName("label_11")
        self.btnevaluate = QtWidgets.QPushButton(self.centralwidget)
        self.btnevaluate.setGeometry(QtCore.QRect(250, 500, 91, 23))
        self.btnevaluate.setObjectName("btnevaluate")
        self.availablePlayersList.raise_()
        self.textBrowser_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.groupBox.raise_()
        self.selectedPlayersList.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.btnevaluate.raise_()
        FastasyCricketGame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FastasyCricketGame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 21))
        self.menubar.setObjectName("menubar")
        self.menuManage_Teams = QtWidgets.QMenu(self.menubar)
        self.menuManage_Teams.setObjectName("menuManage_Teams")
        FastasyCricketGame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FastasyCricketGame)
        self.statusbar.setObjectName("statusbar")
        FastasyCricketGame.setStatusBar(self.statusbar)
        self.actionNew_team = QtWidgets.QAction(FastasyCricketGame)
        self.actionNew_team.setObjectName("actionNew_team")
        self.actionOpen_team = QtWidgets.QAction(FastasyCricketGame)
        self.actionOpen_team.setObjectName("actionOpen_team")
        self.actionSave_team = QtWidgets.QAction(FastasyCricketGame)
        self.actionSave_team.setObjectName("actionSave_team")
        self.actionEvaluate_team = QtWidgets.QAction(FastasyCricketGame)
        self.actionEvaluate_team.setObjectName("actionEvaluate_team")
        self.menuManage_Teams.addAction(self.actionNew_team)
        self.menuManage_Teams.addSeparator()
        self.menuManage_Teams.addAction(self.actionOpen_team)
        self.menuManage_Teams.addSeparator()
        self.menuManage_Teams.addAction(self.actionSave_team)
        self.menuManage_Teams.addSeparator()
        self.menuManage_Teams.addAction(self.actionEvaluate_team)
        self.menubar.addAction(self.menuManage_Teams.menuAction())

        self.retranslateUi(FastasyCricketGame)
        QtCore.QMetaObject.connectSlotsByName(FastasyCricketGame)

    def retranslateUi(self, FastasyCricketGame):
        _translate = QtCore.QCoreApplication.translate
        FastasyCricketGame.setWindowTitle(_translate("FastasyCricketGame", "MainWindow"))
        self.label.setText(_translate("FastasyCricketGame", "Your Selections"))
        self.label_2.setText(_translate("FastasyCricketGame", "Batsmen (BAT)  0"))
        self.label_4.setText(_translate("FastasyCricketGame", "Allrounders (AR)  0"))
        self.label_5.setText(_translate("FastasyCricketGame", "Wicket-keeper (WK)  0"))
        self.label_3.setText(_translate("FastasyCricketGame", "Bowlers (BOW)  0"))
        self.label_6.setText(_translate("FastasyCricketGame", "Points Available 1000"))
        self.label_7.setText(_translate("FastasyCricketGame", "Points used 0"))
        self.groupBox.setTitle(_translate("FastasyCricketGame", "Select Category"))
        self.radioBat.setText(_translate("FastasyCricketGame", "BAT"))
        self.radiobow.setText(_translate("FastasyCricketGame", "BOW"))
        self.radioar.setText(_translate("FastasyCricketGame", "AR"))
        self.radiowk.setText(_translate("FastasyCricketGame", "WK"))
        self.label_10.setText(_translate("FastasyCricketGame", "Available Players"))
        self.label_11.setText(_translate("FastasyCricketGame", "Selected Team"))
        self.btnevaluate.setText(_translate("FastasyCricketGame", "Evaluate Score"))
        self.menuManage_Teams.setTitle(_translate("FastasyCricketGame", "Manage Teams"))
        self.actionNew_team.setText(_translate("FastasyCricketGame", "New team"))
        self.actionOpen_team.setText(_translate("FastasyCricketGame", "Open team"))
        self.actionSave_team.setText(_translate("FastasyCricketGame", "Save team"))
        self.actionEvaluate_team.setText(_translate("FastasyCricketGame", "Evaluate team"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FastasyCricketGame = QtWidgets.QMainWindow()
    ui = Ui_FastasyCricketGame()
    ui.setupUi(FastasyCricketGame)
    FastasyCricketGame.show()
    sys.exit(app.exec_())
